version: '3.4'
services:
  odoo:
    image: odoo:12.0
    ports:
      - 8069:8069
    volumes:
      - odoo-data:/var/lib/odoo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 117.121.212.236:24224
  db:
    image: postgres:10.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  fluentd:
    image: 943049196367.dkr.ecr.ap-southeast-1.amazonaws.com/fluentd
    ports:
      - 24224:24224
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
volumes:
  odoo-data:
  db-data:
